[feat] KValue base class
UnitTestBot/klee pull request #161
Opened 2023-12-12 12:34 UTC by S1eGa

2023-12-14 11:41 UTC, misonijnik requested changes

2023-12-14 11:41 UTC, misonijnik commented on include/klee/Module/KValue.h
> +struct KValue {
Make KValue an abstract class.

2023-12-14 11:41 UTC, misonijnik commented on lib/Expr/SymbolicSource.cpp
> +    if (allocSite->getKind() == ub.allocSite->getKind()) {
KVlaue comparisons must be made within this class.

2023-12-14 11:41 UTC, misonijnik commented on lib/Module/KValue.cpp
> +#include <klee/Module/KValue.h>
< ... > -> " ... "

2023-12-14 11:41 UTC, misonijnik commented on include/klee/Module/KModule.h
> +    return rhs->getKind() == Kind::BLOCK ? classof(cast<KBlock>(rhs)) : false;
Ternary operator -> &&

2023-12-19 10:59 UTC, ocelaiwo requested changes

2023-12-19 10:59 UTC, ocelaiwo commented on lib/Solver/BitwuzlaSolver.cpp
> +    // klee_warning("Empty isConsistent() check");
I think we should attach a comment to this function that will describe what kind of check is to be expected here in the future (or remove this function altogether).

2023-12-19 10:59 UTC, ocelaiwo commented on lib/Expr/SourceBuilder.cpp
> +    unsigned version, const KValue *allocSite, ref<Expr> size) {
We need some way to restrict `allocSite` to those types of `KValue` that make sense as alloc sites. At least make a comment somewhere describing accepted derivatives or make a set of constructors accepting those derivatives only.

2023-12-24 22:06 UTC, ocelaiwo approved these changes

2023-12-25 10:00 UTC, misonijnik approved these changes

2023-12-25 19:06 UTC, merged