Typed KLEE.
UnitTestBot/klee pull request #30
Opened 2022-08-15 16:31 UTC by getN1ght

## Summary: 

## Checklist:
- [ ] The PR addresses a single issue.  If it can be divided into multiple independent PRs, please do so.
- [ ] The PR is divided into a logical sequence of commits OR a single commit is sufficient.
- [ ] There are no unnecessary commits (e.g. commits fixing issues in a previous commit in the same PR).
- [ ] Each commit has a meaningful message documenting what it does.
- [ ] All messages added to the codebase, all comments, as well as commit messages are spellchecked.
- [ ] The code is commented OR not applicable/necessary.
- [ ] The patch is formatted via clang-format OR not applicable (if explicitly overridden leave unchecked and explain).
- [ ] There are test cases for the code you added or modified OR no such test cases are required.

2022-08-20 13:54 UTC, misonijnik requested changes

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +    llvm::cl::desc("Turn's on rules based on strict aliasing rule"),
Add information about the default value

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> -
?

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +      llvm::IntegerType::get(m->getContext(), sizeof(*errno_addr) * 8),
Use named constants instead of literals

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +      if (ati != function->arg_end()) {
Add a comment

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +                                      ref<Expr> value /* def if write*/,
Leave it the same

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +        ObjectState *wos = bound_inner->addressSpace.getWriteable(mo, os);
Maybe it's better to call getWriteable only when the type in the ObjectState changes? At least write a comment

2022-08-20 13:54 UTC, misonijnik commented on lib/Core/Executor.cpp
> +      argvMO = memory->allocate((argc + 1 + envc + 1 + 1) * NumPtrBytes,
Revert changes

2022-08-24 09:17 UTC, ladisgin requested changes

2022-08-24 09:17 UTC, ladisgin commented on lib/Core/Memory.cpp
> +  dynamicType = dt;
move to initialization list

2022-08-24 13:10 UTC, getN1ght commented on lib/Core/Executor.cpp
> +               cl::values(clEnumValN(TypeSystemKind::LLVM, "LLVM",
As KLEE hardly support any other language than C/C++, we do not need it yet

2022-08-24 13:11 UTC, getN1ght commented on lib/Core/Memory.cpp
> +  dynamicType = dt;
?

2022-08-24 14:17 UTC, misonijnik approved these changes

2022-08-24 15:27 UTC, ladisgin approved these changes

2022-08-24 16:03 UTC, merged